status:
    path: /status
    defaults: { _controller: CliftonBundle:Status:status }

aps.find_by_pid:
    path: /aps/programmes/{pid}.json
    methods:  [GET]
    defaults: { _controller: CliftonBundle:FindByPid:findByPid }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

aps.programme_children:
    path: /aps/programmes/{pid}/children.json
    methods:  [GET]
    defaults: { _controller: CliftonBundle:ProgrammeChildren:children }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

aps.music_artist:
    path: /aps/programmes/music/artists/{musicBrainzId}.json
    methods:  [GET]
    defaults: { _controller: CliftonBundle:MusicArtists:show }
    requirements: { musicBrainzId: '[a-f0-9\-]{36}' }

test.availability:
    path: /availability/{pid}.json
    methods:  [GET]
    defaults: { _controller: CliftonBundle:Availability:findByPid }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

home:
    path: /
    methods:  [GET]
    defaults: { _controller: CliftonBundle:Home:home }

debug:
    path: /debug/{serviceName}/{serviceMethod}
    defaults:
        _controller: CliftonBundle:Debug:debug
