parameters:
    clifton.cloudwatch_client_class: Aws\CloudWatch\CloudWatchClient

services:
    security.user.provider.bbc_certificate:
        class: BBC\CliftonBundle\Security\User\BbcCertificateUserProvider

    clifton.cloudwatch_client:
        class: '%clifton.cloudwatch_client_class%'
        arguments:
            - { region: '%aws_s3_region%', version: '2010-08-01' }

    pps.mapper_factory:
        class: BBC\ProgrammesPagesService\Mapper\ProgrammesDbToDomain\MapperFactory
        public: false

    pps.service_factory:
        class: BBC\ProgrammesPagesService\Service\ServiceFactory
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@pps.mapper_factory'

    pps.contributors_service:
        class: BBC\ProgrammesPagesService\Service\ContributorsService
        factory: [ '@pps.service_factory', 'getContributorsService']

    pps.programmes_service:
        class: BBC\ProgrammesPagesService\Service\ProgrammesService
        factory: [ '@pps.service_factory', 'getProgrammesService']

    pps.related_links_service:
        class: BBC\ProgrammesPagesService\Service\RelatedLinksService
        factory: [ '@pps.service_factory', 'getRelatedLinksService']

    pps.segment_events_service:
        class: BBC\ProgrammesPagesService\Service\SegmentEventsService
        factory: [ '@pps.service_factory', 'getSegmentEventsService']

    pps.versions_service:
        class: BBC\ProgrammesPagesService\Service\VersionsService
        factory: [ '@pps.service_factory', 'getVersionsService']
