imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    aws_s3_region: eu-west-1

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    # form:            ~
    # csrf_protection: ~
    validation:      { enable_annotations: false }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    # session:
    #     # handler_id set to null will use default session handler from php.ini
    #     handler_id:  ~
    #     save_path:   "%kernel.root_dir%/../tmp/sessions/%kernel.environment%"
    # fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        server_version: "%database_server_version%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            date_partial: BBC\ProgrammesPagesService\Data\ProgrammesDb\Type\DatePartialType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            ProgrammesPagesService:
                type: annotation
                dir: "%kernel.root_dir%/../vendor/bbc/programmes-pages-service/src/Data/ProgrammesDb/Entity"
                is_bundle: false
                prefix: BBC\ProgrammesPagesService\Data\ProgrammesDb\Entity
        filters:
            embargoed_filter:
                class: BBC\ProgrammesPagesService\Data\ProgrammesDb\Filter\EmbargoedFilter
                enabled: true
        dql:
            string_functions:
                MATCH_AGAINST: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\MatchAgainst
            datetime_functions:
                YEAR: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\Year
                MONTH: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\Month

stof_doctrine_extensions:
    orm:
        default:
            tree: true
            timestampable: true
