# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    kernel.listener.monitoring_listener:
        class: BBC\CliftonBundle\EventListener\MonitoringListener
        arguments:
            - "@monitoring"
            - "clifton"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    monitoring:
        class: RMP\CloudwatchMonitoring\MonitoringHandler
        arguments:
            - "@clifton.cloudwatch_client"
            - "clifton"
            - "%cosmos_environment%"
